#ifndef ABOX_BOOT_VERSION_H
#define ABOX_BOOT_VERSION_H

#ifndef ABOX_BOOT_FW_VERSION
#define ABOX_BOOT_FW_VERSION "abox-boot-2.3.0"
#endif

#define ABOX_BOOT_FW_VERSION_MARKER "ABOX_BOOT_FW_VERSION=" ABOX_BOOT_FW_VERSION
#define ABOX_BOOT_TEST_BUILD 0U
#define ABOX_BOOT_TEST_POINT "NONE"

#endif
