function(abox_hardware_validate target config_dir scheduler)
    if(NOT config_dir OR NOT EXISTS "${config_dir}/abox_product_config.h")
        message(FATAL_ERROR "stm32f105_ec800_v1 requires abox_product_config.h")
    endif()
    file(READ "${config_dir}/abox_product_config.h" product_config)
    if(NOT product_config MATCHES "ABOX_SCHEDULER_${scheduler}")
        message(FATAL_ERROR "stm32f105_ec800_v1 scheduler disagrees with product config")
    endif()
    target_include_directories(${target} PRIVATE "${config_dir}")
endfunction()
