function(abox_platform_attach target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "abox_platform_attach: target '${target}' does not exist")
    endif()

    target_link_libraries(${target} abox::core)
    target_link_libraries(${target} abox::ec_power)
    if(NOT DEFINED ABOX_PLATFORM_USE_CJSON OR ABOX_PLATFORM_USE_CJSON)
        target_link_libraries(${target} abox::cjson)
    endif()

    if(ABOX_PLATFORM_SCHEDULER STREQUAL "FREERTOS")
        target_link_libraries(${target} abox::port_freertos)
    else()
        target_link_libraries(${target} abox::port_baremetal)
    endif()

    if(ABOX_PRODUCT_CONFIG_DIR)
        target_include_directories(${target} PRIVATE "${ABOX_PRODUCT_CONFIG_DIR}")
    endif()
endfunction()

function(abox_platform_attach_boot target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "abox_platform_attach_boot: target '${target}' does not exist")
    endif()

    target_link_libraries(${target} abox::boot abox::ota abox::ec_power)

    if(ABOX_PRODUCT_CONFIG_DIR)
        target_include_directories(${target} PRIVATE "${ABOX_PRODUCT_CONFIG_DIR}")
    endif()
endfunction()

function(abox_platform_attach_boot_v2_app target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "abox_platform_attach_boot_v2_app: target '${target}' does not exist")
    endif()
    target_link_libraries(${target} abox::boot_v2_app)
    if(ABOX_PRODUCT_CONFIG_DIR)
        target_include_directories(${target} PRIVATE "${ABOX_PRODUCT_CONFIG_DIR}")
    endif()
endfunction()

function(abox_platform_attach_boot_v2 target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "abox_platform_attach_boot_v2: target '${target}' does not exist")
    endif()
    target_link_libraries(${target} abox::boot_v2_boot abox::ec_power)
    if(ABOX_PRODUCT_CONFIG_DIR)
        target_include_directories(${target} PRIVATE "${ABOX_PRODUCT_CONFIG_DIR}")
    endif()
endfunction()
