function(abox_platform_attach_components target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "abox_platform_attach_components: target '${target}' does not exist")
    endif()
    cmake_parse_arguments(ABOX "" "SCHEDULER;HARDWARE" "COMPONENTS" ${ARGN})
    if(ABOX_UNPARSED_ARGUMENTS OR ABOX_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "abox_platform_attach_components: invalid arguments")
    endif()
    if(NOT ABOX_SCHEDULER MATCHES "^(BAREMETAL|FREERTOS)$")
        message(FATAL_ERROR "abox_platform_attach_components: SCHEDULER must be BAREMETAL or FREERTOS")
    endif()
    if(NOT ABOX_COMPONENTS)
        message(FATAL_ERROR "abox_platform_attach_components: COMPONENTS is required")
    endif()
    if(ABOX_HARDWARE)
        set(hardware_contract "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../targets/${ABOX_HARDWARE}/HardwareContract.cmake")
        if(NOT EXISTS "${hardware_contract}")
            message(FATAL_ERROR "abox_platform_attach_components: unknown HARDWARE '${ABOX_HARDWARE}'")
        endif()
        include("${hardware_contract}")
        abox_hardware_validate(${target} "${ABOX_PRODUCT_CONFIG_DIR}" "${ABOX_SCHEDULER}")
    endif()
    string(TOLOWER "${ABOX_SCHEDULER}" scheduler_target)
    target_link_libraries(${target} abox::port_${scheduler_target})
    foreach(component IN LISTS ABOX_COMPONENTS)
        if(component STREQUAL "boot" OR component STREQUAL "ota")
            message(FATAL_ERROR "abox_platform_attach_components: legacy Boot/OTA must be attached explicitly")
        endif()
        if(NOT component MATCHES "^(core|cjson|ec_power|ec800|ec800_ufs|ec800_command_port|ec800_tls|mqtt_tls|mqtt_runtime|mqtt_trial|mqtt_v4|mqtt_ec800_rx|mqtt_ec800|enrollment|enrollment_ec800_http|boot_v2_common|boot_v2_app|https_ufs_downloader)$")
            message(FATAL_ERROR "abox_platform_attach_components: unknown component '${component}'")
        endif()
        if(NOT TARGET abox::${component})
            message(FATAL_ERROR "abox_platform_attach_components: unavailable component '${component}'")
        endif()
        target_link_libraries(${target} abox::${component})
    endforeach()
    foreach(requirement IN ITEMS
            "ec_power:core" "ec800_command_port:ec800" "ec800_tls:ec800_ufs"
            "mqtt_tls:ec800_tls" "mqtt_runtime:mqtt_tls"
            "mqtt_runtime:ec800_command_port" "mqtt_ec800:ec800"
            "mqtt_ec800:mqtt_ec800_rx" "enrollment:cjson"
            "enrollment_ec800_http:ec800" "boot_v2_common:core"
            "boot_v2_app:boot_v2_common" "boot_v2_app:https_ufs_downloader")
        string(REPLACE ":" ";" pair "${requirement}")
        list(GET pair 0 selected)
        list(GET pair 1 dependency)
        if(selected IN_LIST ABOX_COMPONENTS AND NOT dependency IN_LIST ABOX_COMPONENTS)
            message(FATAL_ERROR
                "abox_platform_attach_components: '${selected}' requires '${dependency}'")
        endif()
    endforeach()
endfunction()

function(abox_platform_attach target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "abox_platform_attach: target '${target}' does not exist")
    endif()

    target_link_libraries(${target} abox::core)
    target_link_libraries(${target} abox::ec_power)
    if(NOT DEFINED ABOX_PLATFORM_USE_CJSON OR ABOX_PLATFORM_USE_CJSON)
        target_link_libraries(${target} abox::cjson)
    endif()

    if(ABOX_PLATFORM_SCHEDULER STREQUAL "FREERTOS")
        target_link_libraries(${target} abox::port_freertos)
    else()
        target_link_libraries(${target} abox::port_baremetal)
    endif()

    if(ABOX_PRODUCT_CONFIG_DIR)
        target_include_directories(${target} PRIVATE "${ABOX_PRODUCT_CONFIG_DIR}")
    endif()
endfunction()

function(abox_platform_attach_mqtt target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "abox_platform_attach_mqtt: target '${target}' does not exist")
    endif()
    cmake_parse_arguments(ABOX_MQTT "" "VERSION" "" ${ARGN})
    if(NOT ABOX_MQTT_VERSION STREQUAL "4")
        message(FATAL_ERROR "abox_platform_attach_mqtt currently supports VERSION 4")
    endif()
    target_link_libraries(${target} abox::mqtt_v4 abox::ec800)
endfunction()

function(abox_platform_attach_boot target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "abox_platform_attach_boot: target '${target}' does not exist")
    endif()

    target_link_libraries(${target} abox::boot abox::ota abox::ec_power)

    if(ABOX_PRODUCT_CONFIG_DIR)
        target_include_directories(${target} PRIVATE "${ABOX_PRODUCT_CONFIG_DIR}")
    endif()
endfunction()

function(abox_platform_attach_boot_v2_app target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "abox_platform_attach_boot_v2_app: target '${target}' does not exist")
    endif()
    target_link_libraries(${target} abox::boot_v2_app)
    if(ABOX_PRODUCT_CONFIG_DIR)
        target_include_directories(${target} PRIVATE "${ABOX_PRODUCT_CONFIG_DIR}")
    endif()
endfunction()

function(abox_platform_attach_boot_v2 target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "abox_platform_attach_boot_v2: target '${target}' does not exist")
    endif()
    target_link_libraries(${target} abox::boot_v2_boot abox::ec_power)
    if(ABOX_PRODUCT_CONFIG_DIR)
        target_include_directories(${target} PRIVATE "${ABOX_PRODUCT_CONFIG_DIR}")
    endif()
endfunction()
